package com.splitpay.app.model

/**
 * Represents a single installment in a split-payment sequence.
 *
 * Replaces the parallel `splits[]`, `paid[]`, `failed[]` arrays that
 * previously existed only inside the JS runtime. The Kotlin side uses
 * this class when it needs to reason about parts (e.g. in logging,
 * analytics callbacks, or future server sync).
 *
 * [index]  0-based position in the sequence.
 * [amount] Rupee amount (integer — no paise to avoid float rounding).
 * [ref]    Ledger reference generated by makeRef() in state.js.
 * [status] Current lifecycle status.
 */
data class SplitPart(
    val index: Int,
    val amount: Int,
    val ref: String,
    val status: PartStatus = PartStatus.PENDING,
) {
    enum class PartStatus {
        /** Not yet launched. */
        PENDING,
        /** UPI app confirmed success (or user marked done). */
        PAID,
        /** User marked failed or sequence cancelled mid-flight. */
        FAILED,
        /** Skipped by user during auto sequence. */
        SKIPPED,
    }

    // ── Computed convenience ───────────────────────────────────────

    /** Human-readable 1-based index ("Part 3 of 5"). */
    val displayIndex get() = index + 1

    val isPending  get() = status == PartStatus.PENDING
    val isPaid     get() = status == PartStatus.PAID
    val isFailed   get() = status == PartStatus.FAILED
    val isSkipped  get() = status == PartStatus.SKIPPED
    val isComplete get() = status != PartStatus.PENDING

    /** Amount formatted with Indian locale grouping (₹1,999). */
    val displayAmount get() = "₹${String.format("%,d", amount)}"

    /** Outcome emoji for compact receipt rendering. */
    val statusIcon get() = when (status) {
        PartStatus.PAID    -> "✓"
        PartStatus.FAILED  -> "✕"
        PartStatus.SKIPPED -> "⏭"
        PartStatus.PENDING -> "…"
    }

    /** Returns a copy with updated status (immutable-friendly). */
    fun asPaid()    = copy(status = PartStatus.PAID)
    fun asFailed()  = copy(status = PartStatus.FAILED)
    fun asSkipped() = copy(status = PartStatus.SKIPPED)
}
